export const INIT_GRAPH = 'init_graph'
export const ADD_NODE = 'add_node'
export const REMOVE_NODE = 'remove_node'
export const UPDATE_NODE = 'update_node'
export const ADD_GRAPH_FILTER = 'add_graph_filter'
export const CLEAR_GRAPH_FILTER = 'clear_graph_filter'
export const CHANGE_LAYOUT_DIRECTION = 'change_layout_direction'
export const TOGGLE_LABEL_VISIBILITY = 'toggle_label_visibility'